### ISSUE TITLE
Implement Session Registration

### ISSUE THREAD

**Issue by TgkCapture** [My-Code-Incubator/Login-Automation#5]
Develop the functionality to automate the initial session registration process by sending a request to the [JSONPlaceholder for Development](https://jsonplaceholder.typicode.com/posts) endpoint to obtain a client ID/user id.

Tasks:

1. Create a new endpoint /register_session in the Flask application.

2. Capture necessary parameters (user agent, device ID, signature) from the request body.

3. Send a POST request to https://jsonplaceholder.typicode.com/posts with the captured parameters.

4. Handle the response to extract and return the client ID.

**Comment by TgkCapture** [comment]
@KentChunga making progress?

**Comment by KentChunga** [comment]
> @KentChunga making progress?

Yeah, there is progress.
