### ISSUE TITLE
Implement Browser Authentication with Mock Site

### ISSUE THREAD

**Issue by TgkCapture** [My-Code-Incubator/Login-Automation#6]
Develop the functionality to automate browser interactions for entering the username and password using Selenium or any other suitable alternative.

Tasks:

1. Create a new endpoint `/authenticate_browser`
2. Capture necessary parameters (device ID, username, password) from the request body.
3. Use Selenium to open the browser and navigate to `https://example.com/`
4. Automate the login process by entering the username and password.
5. Capture the access token upon successful login.

On this one just be creative since the actual site we initially planned to use is a no go zone for us. So look up mock sites that can suit the tests.

**Comment by HBFLEX** [comment]
Alright so i have assigned myself this task, i will try to get it done
